name: CFFormat

on:
  push:
    branches-ignore:
      - "main"
      - "master"
      - "development"
    paths:
      - '**.cfc' # Only run if *.cfc files are modified
  pull_request:
    branches:
      - main
      - master
      - development
    paths:
      - '**.cfc' # Only run if *.cfc files are modified

jobs:
  format:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Run CFFormat
        uses: Ortus-Solutions/commandbox-action@v1
        with:
          cmd: cfformat run path=models,tests/specs --overwrite

      - name: Commit Format Changes
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "👌 IMPROVE: Auto-format cfcs via cfformat"